services:
  # Redis service
  - type: redis
    name: mybizsherpa-redis
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  # FastAPI Web Service
  - type: web
    name: mybizsherpa-api-v2
    runtime: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME  # Just the repo URL
    branch: main
    rootDir: backend  # This tells Render to look in the backend folder
    dockerfilePath: ./Dockerfile  # Relative to rootDir (so backend/Dockerfile)
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: mybizsherpa-redis
          property: connectionString

  # Celery Worker Service  
  - type: worker
    name: mybizsherpa-worker
    runtime: docker
    repo: https://github.com/rutvija-mali/mybizsherpa-project  # Same repo URL
    branch: main
    rootDir: backend  # This is the key - points to backend folder
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A celery_app worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: mybizsherpa-redis
          property: connectionString